export enum postTypes {
    CHANGE_CURRENT_POST = "CHANGE_CURRENT_POST",
    FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST",
    FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS",
    FETCH_POSTS_FAILURE = "FETCH_POSTS_FAILURE",
}
